### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by schoeps** [davidalber/geneagrapher#22]
Is anyone working on porting the code to python 3? I tried my luck with `2to3` but there is still a few remaining issues that require a careful look. Before I dig deep into the code, I wanted to check if this is already done? Thanks!

**Comment by davidalber** [comment]
Hi, @schoeps! No, I'm not actively working on porting this code to support Python 3, and I'm not aware of anyone else doing it, either. If you decide to keep going with it, I'd be happy to look at any pull requests, including drafts, if you are stuck on something or have something you think is mergeable.

Thanks for your interest!

**Comment by d-torrance** [comment]
Stuart Prescott ported the Debian package of geneagrapher to Python 3 a few months ago.  I'll prepare a pull request here in a moment with the patches.

**Comment by schoeps** [comment]
I checked out fork #23. It works for me. I needed to modify the http fetching in line 28 `page = urllib.request.urlopen(url,context=ssl._create_unverified_context())`
of `geneagrapher/grabber.py` to avoid certificate errors. I am not sure if my Mac is guilty or the server. It seems that the website moves to http://mathgenealogy.org. 

@davidalber: maybe it's time for a new release :)
