### ISSUE TITLE
Update Math Genealogy Project URL

### ISSUE THREAD

**Issue by davidalber** [davidalber/geneagrapher#24]
As mentioned in [this comment](https://github.com/davidalber/geneagrapher/issues/22#issuecomment-653797962) of #22, the Math Genealogy Project website moved. The URL in Geneagrapher needs to be updated and SSL verification issues overcome.

**Comment by schoeps** [comment]
I guess for now adding `context=ssl._create_unverified_context()` to
https://github.com/davidalber/geneagrapher/blob/4a7df5c8f371b9d7df65694dbe1901972216feab/geneagrapher/grabber.py#L28

is the most reasonable approach. I'd say we are not dealing with very dangerous data so we can survive without certificate. Shall I create a Pull request?

**Comment by davidalber** [comment]
@schoeps: Making the requests without verifying the SSL certificate doesn't feel good to me, but I'm fine if you create a PR along those lines for right now. Thanks!
