### ISSUE TITLE
Wrong formatted json output

### ISSUE THREAD

**Issue by empet** [davidalber/geneagrapher#34]
I experimented how the last geneagrapher  version works. I'm interested in json output, which can be used with pyhon `networkx`, `igraph`, and julia `Graphs.jl`.
The json option for output   creates a file which isn't a json formatted `dict`, and cannot be read by python `json` or julia `JSON`. (Here is a file  [https://github.com/empet/Datasets/blob/master/strogatz.json](https://github.com/empet/Datasets/blob/master/strogatz.json)).
With the actual format, an attempt to read it with Python:
``` 
import json
with open('strogatz.json', 'r') as fp:
    jdata = json.load( fp)
```
ends with this error:
```
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
A file structure, defined as below, would be fine, and doesn't require  many additions to the actual code of 
`geneagrapher`:
```
{
 "nodes":[{"id": 1, "label": "Mathematician1\nUniversiy of Texas at Austin"},
          {"id": 2, "label": "Mathematician2\nCornell University"}, 
          {"id": 3, "label": "Mathematician3\nUCLA"}],
 "edges":[[1,2], [1,3]]
}
```
To be able to setup a  tree structure from the json file generated by geneagrapher, I copied the nodes and labels into a csv file, and edges into another one, obviously with many `find and replace` to get right data to be saved as columns in a csv file. Here is the corresponding tree resulted by processing and plotting the tree data with a few Julia packages, and custom functions: [https://nbviewer.org/gist/empet/e4887c789c5d276688752db7d218de31](https://nbviewer.org/gist/empet/e4887c789c5d276688752db7d218de31). It is an interactive plot.

**Comment by szhorvat** [comment]
> (Here is a file https://github.com/empet/Datasets/blob/master/strogatz.json).

I am not involved with this project, but I can tell you that this is not JSON. It is a Graphviz DOT file.

It is useful if you want to visualize the network with Graphviz, but it's not ideal as an exchange format due to the difficulty of implementing a complete parser for it.

**Comment by empet** [comment]
The author says here [https://pypi.org/project/geneagrapher/](https://pypi.org/project/geneagrapher/) that data can be saved  in json format, too. I checked the geneagrapher code and it's clear that it contains if statements of the form
`if json....`.

**Comment by davidalber** [comment]
Hi, @empet. Thank you for using Geneagrapher and reporting the issue you were experiencing. Also, thank you @szhorvat for jumping in and assisting!

Although the cause of the issue was a missing flag (`-f`) in the command, more complete documentation probably could have helped avoid the confusion. I have added a new example to the README in #35 that shows how to produce JSON output.

Thanks again for filing this issue!
