### ISSUE TITLE
Third party use of WebSocket endpoint

### ISSUE THREAD

**Issue by louisaslett** [davidalber/geneagrapher#38]
Thank you for creating such great software!

As primarily an R user, I’ve been considering developing an interface package in R. However, before proceeding, I wanted to ask for your permission to have other software query your `wss://ggrphr.davidalber.net` endpoint. I’ve reviewed the source code and understand the JSON encoding, so I’m confident I can implement this in R. Of course, I would credit you appropriately for running the endpoint that provides the data. Would you be comfortable with this?

Thanks!

**Comment by davidalber** [comment]
Hi, @louisaslett. Yes, I am happy for you to use the Geneagrapher WebSocket interface. When doing so, please set a user agent that identifies traffic from your package. For instance, for a user running Python 3.12.6, the code in this repository currently sets a user agent of "Python/3.12.6 Geneagrapher/2.0.0", which is done in the code [here](https://github.com/davidalber/geneagrapher/blob/a05b3c51004b57981b2476ed0b07b2886d738269/geneagrapher/geneagrapher.py#L158).

For your package, a user agent of something like "R/`R_VERSION` `PACKAGE_NAME`/`PACKAGE_VERSION`" would follow the existing pattern.

Thank you for your interest in using the backend, and feel free to reach out if you have any questions.

**Comment by louisaslett** [comment]
That's great, thanks so much! Yes, I'll be sure to set a user agent string as requested.

I'm making a (slow) start on development at [louisaslett/maths.genealogy](https://github.com/louisaslett/maths.genealogy)
