### ISSUE TITLE
Geneagrapher backend down?

### ISSUE THREAD

**Issue by louisaslett** [davidalber/geneagrapher#39]
I've tried a few times over the past 12 hours and I'm getting the following error:

```
Geneagrapher backend is currently unavailable.:::::::::::::::::::::::::] 0/1

If this problem persists, please create an issue at
https://github.com/davidalber/geneagrapher/issues/new, and include the
following in the issue body:

    Message: Geneagrapher backend is currently unavailable.
    Command: /Users/louis/temp/ggrapher/bin/ggrapher -o tree.dot 18231:a
```

Version info:

```
% ggrapher --version
ggrapher 2.0.0
```

**Comment by davidalber** [comment]
Hello. Thank you for the report!

The Geneagrapher backend was intermittently emitting exceptions over the past couple of months, but the exceptions seemed to only occasionally affect requests. I did not notice that the exception recently changed. It looks similar, but is actually different and affects, as you pointed out, 100% of requests.

I tracked the issue down to a Redis connection string environment variable the application depends on being removed by the compute platform the Geneagrapher backend is hosted on. I've updated the application to use the new environment variable and the backend is working again.

You should be able to use `ggrapher` again, and no update is needed for it as this was completely a backend issue. Please let me know if it's not actually fixed for you.

Thanks again!

**Comment by louisaslett** [comment]
Perfect, working again many thanks!

**Comment by davidalber** [comment]
Great! Thank you for following up to let me know that the issue is resolved for you.
